image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - ls -l
    - ls -l dist
    - mkdir -p public
    - cp -av --recursive dist/* public/
    - ls -lR public
  artifacts:
    paths:
      - public
      - public/*
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
