image: harbor.uni-muenster.de/proxy-docker/library/node:latest

stages:
  - test
  - deploy

build-and-run-tests:
  stage: test
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - npm run test
  artifacts:
    paths:
      - dist

# push to npm package registry
deploy:
  stage: deploy
  script:
    - echo "@scdh:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - cat .npmrc
    - npm publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


pages:
  stage: deploy
  script:
    - ls -l
    - ls -l dist
    - mkdir -p public
    - cp -av --recursive dist/* public/
    - ls -lR public
  artifacts:
    paths:
      - public
      - public/*
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
